In [1]:
import pandas as pd

# Load dataset
df = pd.read_csv("smart_home_energy_consumption_large.csv")


df.head()

,Home ID,Appliance Type,Energy Consumption (kWh),Time,Date,Outdoor Temperature (°C),Season,Household Size
0,94,Fridge,0.20,21:12,2023-12-02,-1.0,Fall,2.0
1,435,Oven,0.23,20:11,2023-08-06,31.1,Summer,5.0
2,466,Dishwasher,0.32,06:39,2023-11-21,21.3,Fall,3.0
3,496,Heater,3.92,21:56,2023-01-21,-4.2,Winter,1.0
4,137,Microwave,0.44,04:31,2023-08-26,34.5,Summer,5.0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21756 entries, 0 to 21755
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Home ID                   21756 non-null  int64
 1   Appliance Type            21756 non-null  object
 2   Energy Consumption (kWh)  21755 non-null  float64
 3   Time                      21755 non-null  object
 4   Date                      21755 non-null  object
 5   Outdoor Temperature (°C)  21755 non-null  float64
 6   Season                    21755 non-null  object
 7   Household Size            21755 non-null  float64
dtypes: float64(3), int64(1), object(4)
memory usage: 1.3+ MB

In [3]:
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21755 entries, 0 to 21754
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Home ID                   21755 non-null  int64
 1   Appliance Type            21755 non-null  object
 2   Energy Consumption (kWh)  21755 non-null  float64
 3   Time                      21755 non-null  object
 4   Date                      21755 non-null  object
 5   Outdoor Temperature (°C)  21755 non-null  float64
 6   Season                    21755 non-null  object
 7   Household Size            21755 non-null  float64
dtypes: float64(3), int64(1), object(4)
memory usage: 1.5+ MB

In [5]:
df['datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'])

In [6]:
df = df.set_index('datetime')

In [7]:
df.head()

,Home ID,Appliance Type,Energy Consumption (kWh),Time,Date,Outdoor Temperature (°C),Season,Household Size
datetime,,,,,,,,
2023-12-02 21:12:00,94,Fridge,0.20,21:12,2023-12-02,-1.0,Fall,2.0
2023-08-06 20:11:00,435,Oven,0.23,20:11,2023-08-06,31.1,Summer,5.0
2023-11-21 06:39:00,466,Dishwasher,0.32,06:39,2023-11-21,21.3,Fall,3.0
2023-01-21 21:56:00,496,Heater,3.92,21:56,2023-01-21,-4.2,Winter,1.0
2023-08-26 04:31:00,137,Microwave,0.44,04:31,2023-08-26,34.5,Summer,5.0

In [8]:
df = df.drop(columns=['Date', 'Time'])

In [9]:
df['hour'] = df.index.hour
df['day'] = df.index.day
df['weekday'] = df.index.weekday      # 0 = Monday
df['month'] = df.index.month

In [10]:
df[['hour', 'day', 'weekday', 'month']].head()

                     hour  day  weekday  month
datetime
2023-12-02 21:12:00    21    2        5     12
2023-08-06 20:11:00    20    6        6      8
2023-11-21 06:39:00     6   21        1     11
2023-01-21 21:56:00    21   21        5      1
2023-08-26 04:31:00     4   26        5      8

In [11]:
df = df.sort_index()

In [12]:
df['lag_1'] = df.groupby('Appliance Type')['Energy Consumption (kWh)'].shift(1)
df['lag_24'] = df.groupby('Appliance Type')['Energy Consumption (kWh)'].shift(24)

df['rolling_mean_24'] = (
    df.groupby('Appliance Type')['Energy Consumption (kWh)']
      .shift(1)
      .rolling(window=24)
      .mean()
)

In [13]:
df = df.dropna()

In [14]:
df[['Energy Consumption (kWh)', 'lag_1', 'lag_24', 'rolling_mean_24']].head()

                     Energy Consumption (kWh)  lag_1  lag_24  rolling_mean_24
datetime
2023-01-03 23:16:00                      0.17   0.46    0.30         1.347500
2023-01-03 23:25:00                      0.60   1.42    0.36         1.266667
2023-01-03 23:26:00                      0.14   0.17    0.29         1.267500
2023-01-04 03:00:00                      0.23   0.14    0.46         1.361667
2023-01-04 03:33:00                      0.22   0.23    0.39         1.358333